version: '3.1'

services:
  db:
    image: postgres:14.5
    container_name: ng-cash-backend
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=ng-cash-db
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
